name: Drive

on:
  push:
    branches: [ "main" ]
# new release for testing
jobs:
  package:
    name: Upload (drive) APK for test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install keystore and keystore.properties
        env:
          KEYSTORE_PROPERTIES_BASE64: ${{ secrets.KEYSTORE_PROPERTIES }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          KEYSTORE_PROPERTIES_PATH=${{ github.workspace }}/keystore.properties
          echo -n "$KEYSTORE_PROPERTIES_BASE64" | base64 -d > $KEYSTORE_PROPERTIES_PATH

          KEYSTORE_PATH=${{ github.workspace }}/keystore_deploy
          echo -n "$KEYSTORE_BASE64" | base64 -d > $KEYSTORE_PATH

          ls $RUNNER_TEMP

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: 'app/build/outputs/apk/debug/app-debug.apk'

      #- name: Upload apk to Google Drive
      #  uses: Jodebu/upload-to-drive@master
      #  with:
      #    target: 'app/build/outputs/apk/debug/app-debug.apk'
      #    credentials: ${{ secrets.DRIVE_CREDENTIALS }}
      #    folder: '1c26HP_iwA6iQIQrevPUXc9h2q7NoqMNr'
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          filename: "app/build/outputs/apk/debug/app-debug.apk"
          folderId: '1c26HP_iwA6iQIQrevPUXc9h2q7NoqMNr'
          #name: "documentation.zip" # optional string
          overwrite: "false" # optional boolean

      - name: Clean files
        if: ${{ always() }}
        run: |
          rm ${{ github.workspace }}/keystore.properties
          rm ${{ github.workspace }}/keystore_deploy