name: App build (for test)

on:
  push:
    branches: ["main"]
# new release for testing
jobs:
  package:
    name: Generate APK for test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install keystore and keystore.properties
        env:
          KEYSTORE_PROPERTIES_BASE64: ${{ secrets.KEYSTORE_PROPERTIES }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          KEYSTORE_PROPERTIES_PATH=/keystore.properties
          echo -n "$KEYSTORE_PROPERTIES_BASE64" | base64 -d > $KEYSTORE_PROPERTIES_PATH

          KEYSTORE_PATH=/keystore_deploy
          echo -n "$KEYSTORE_BASE64" | base64 -d > $KEYSTORE_PATH

          ls $RUNNER_TEMP

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: 'app/build/outputs/apk/debug/app-debug.apk'

      - name: Clean files
        if: ${{ always() }}
        run: |
          rm /keystore.properties
          rm /keystore_deploy