name: App build

on:
  push:
    tags:
      - release-**

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install keystore and keystore.properties
        env:
          KEYSTORE_PROPERTIES_BASE64: ${{ secrets.KEYSTORE_PROPERTIES }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          KEYSTORE_PROPERTIES_PATH=/home/runner/work/movies/android/keystore.properties
          echo -n "$KEYSTORE_PROPERTIES_BASE64" | base64 -d > $KEYSTORE_PROPERTIES_PATH
          
          KEYSTORE_PATH=/home/runner/work/movies/android/app/KeyStore
          echo -n "$KEYSTORE_BASE64" | base64 -d > $KEYSTORE_PATH
          
          ls $RUNNER_TEMP

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

  build-apk:
    needs: [init]
    runs-on: ubuntu-latest
    steps:
      - name: Build release apk
        run: ./gradle2 assembleRelease --stacktrace

      - name: Upload apk
        uses: actions/upload-artifact@master
        with:
          name: app-release
          path: app/build/outputs/bundle/release/app-release.apk

      - name: Clean files
        if: ${{ always() }}
        run: |
          rm /home/runner/work/movies/android/keystore.properties
          rm /home/runner/work/movies/android/app/KeyStore
          

  build-aab:
    needs: [init]
    runs-on: ubuntu-latest
    steps:
      - name: Build release aab
        run: ./gradlew bundleRelease --stacktrace

      - name: Upload aab
        uses: actions/upload-artifact@master
        with:
          name: app-release #test-${{ github.ref_name }}
          path: app/build/outputs/bundle/release/app-release.aab

      #- name: Publish to Play Store beta track
      #  uses: r0adkll/upload-google-play@v1.0.19
      #  with:
      #    serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      #    packageName: com.fourleaflabs.cicd
      #    releaseFiles: app/build/outputs/bundle/release/app-release.aab
      #    track: beta
      #    status: draft
      #    inAppUpdatePriority: 2

      - name: Clean files
        if: ${{ always() }}
        run: |
          rm /home/runner/work/movies/android/keystore.properties
          rm /home/runner/work/movies/android/app/KeyStore