name: Update JSON on Commit to Main

on:
  push:
    branches:
      - main

jobs:
  package:
    name: Upload APK for test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install keystore and keystore.properties
        env:
          KEYSTORE_PROPERTIES_BASE64: ${{ secrets.KEYSTORE_PROPERTIES }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          KEYSTORE_PROPERTIES_PATH=${{ github.workspace }}/keystore.properties
          echo -n "$KEYSTORE_PROPERTIES_BASE64" | base64 -d > $KEYSTORE_PROPERTIES_PATH

          KEYSTORE_PATH=${{ github.workspace }}/keystore_deploy
          echo -n "$KEYSTORE_BASE64" | base64 -d > $KEYSTORE_PATH

          ls $RUNNER_TEMP

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build debug APK
        run: ./gradlew assembleFlavorFirstRelease --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: 'app/build/outputs/apk/flavorFirst/release/*.apk'

      - name: Clean files
        run:
          rm ${{ github.workspace }}/app/build/outputs/apk/flavorFirst/release/*.json

      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
          aws_key_id: ${{secrets.AWS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: autoupload-testing/apks
          #destination_dir: 4leaflabs-orderspoon/apk/pos/
          source_dir: 'app/build/outputs/apk/flavorFirst/release'
      - name: Check files
        run:
          ls

      - name: Clean files
        if: ${{ always() }}
        run: |
          rm ${{ github.workspace }}/keystore.properties
          rm ${{ github.workspace }}/keystore_deploy

  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Download JSON file from S3
        run: |
          aws s3 cp s3://autoupload-testing/versions.json versions.json

      - name: Generate file name and date
        id: generate-info
        run: |
          echo "file_name=$(date +"%Y%m%d%H%M%S")-x" >> $GITHUB_ENV
          echo "current_date=$(date +"%Y%m%d")" >> $GITHUB_ENV
          apk_file_name=$(basename app/build/outputs/apk/flavorFirst/release/app-flavorFirst-release-unsigned.apk)
          echo "apk_file_name=$apk_file_name" >> $GITHUB_ENV

      - name: Modify JSON file
        run: |
          file_name=${{ env.file_name }}
          current_date=${{ env.current_date }}
          jq --arg version "$file_name" --arg date "$current_date" '
             .kd.version = $version |
             .kd.lastUpdate = ($date | tonumber)
          ' versions.json > versions_modified.json

      - name: Upload modified JSON file to S3
        run: |
          aws s3 cp versions_modified.json s3://autoupload-testing/versions.json