name: Upload apk

on:
  push:
    branches: [ "main" ]
# new release for testing
jobs:
  package:
    name: Upload APK for test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install keystore and keystore.properties
        env:
          KEYSTORE_PROPERTIES_BASE64: ${{ secrets.KEYSTORE_PROPERTIES }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          KEYSTORE_PROPERTIES_PATH=${{ github.workspace }}/keystore.properties
          echo -n "$KEYSTORE_PROPERTIES_BASE64" | base64 -d > $KEYSTORE_PROPERTIES_PATH

          KEYSTORE_PATH=${{ github.workspace }}/keystore_deploy
          echo -n "$KEYSTORE_BASE64" | base64 -d > $KEYSTORE_PATH

          ls $RUNNER_TEMP

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: 'app/build/outputs/apk/debug/app-debug.apk'

      - name: test
        run: |
          cd 'app'
          echo "*app"
          ls
          cd 'build'
          echo "*build"
          ls
          cd 'outputs'
          echo "*outputs"
          ls
          cd 'apk'
          echo "*apk"
          ls
          cd 'debug'
          echo "*debug"
          ls
          

      - name: github-action-push-to-another-repository
        uses: nkoppel/push-files-to-another-repository@v1.1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'app'#/build/outputs/apk/debug/app-debug.apk'
          destination-username: 'xchel4leaflabs'
          destination-repository: 'TestApks'
          # destination-directory: 'projects/my-project'
          commit-email: 'xchel.co@gmail.com'
          destination-branch: 'main'

      - name: Clean files
        if: ${{ always() }}
        run: |
          rm ${{ github.workspace }}/keystore.properties
          rm ${{ github.workspace }}/keystore_deploy