name: Upload apk

on:
  push:
    branches: [ "main" ]
# new release for testing
jobs:
  package:
    name: Upload APK for test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install keystore and keystore.properties
        env:
          KEYSTORE_PROPERTIES_BASE64: ${{ secrets.KEYSTORE_PROPERTIES }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          KEYSTORE_PROPERTIES_PATH=${{ github.workspace }}/keystore.properties
          echo -n "$KEYSTORE_PROPERTIES_BASE64" | base64 -d > $KEYSTORE_PROPERTIES_PATH

          KEYSTORE_PATH=${{ github.workspace }}/keystore_deploy
          echo -n "$KEYSTORE_BASE64" | base64 -d > $KEYSTORE_PATH

          ls $RUNNER_TEMP

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build debug APK
        run: ./gradlew assembleFlavorFirstRelease --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: 'app/build/outputs/apk/flavorFirst/release/*.apk'

      #- name: Pushes test file
      #  uses: dmnemec/copy_file_to_another_repo_action@main
      #  env:
      #    API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #  with:
      #    source_file: 'app/build/outputs/apk/debug/app-debug.apk'
      #    destination_repo: 'xchel4leaflabs/TestApks'
      #    destination_folder: '/sandbox/'
      #    user_email: 'xchel@4leaflabs.com'
      #    user_name: 'xchel4leaflabs'
      #    commit_message: 'test'

      - name: Upload to S3
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
          aws_key_id: ${{secrets.AWS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: autoupload-testing
          source_dir: 'app/build/outputs/apk/flavorFirst/release/*.apk'

      - name: Clean files
        if: ${{ always() }}
        run: |
          rm ${{ github.workspace }}/keystore.properties
          rm ${{ github.workspace }}/keystore_deploy